import Head from 'next/head'
import type { AppProps } from 'next/app'

// add bootstrap css 
import 'bootstrap/dist/css/bootstrap.css'
// own css files here
// import "../css/customcss.css";

function MyApp({ Component, pageProps }: AppProps) {
  return <>
    <Head>
        <title>Teste Veggi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
  <Component {...pageProps} />
  </>
}

export default MyApp
