import Head from "next/head";
import type { AppProps } from "next/app";
import { Header } from "../components/Header";

// add bootstrap css
import "bootstrap/dist/css/bootstrap.css";
import React from "react";
// own css files here
import "../styles/globals.css";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Crud Veggi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
